# Generated by Django 3.0.3 on 2020-06-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_extendeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extendeduser',
        ),
    ]
