# Generated by Django 3.0.3 on 2020-06-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_extendeduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignments',
            new_name='Assignment',
        ),
        migrations.RenameModel(
            old_name='upload',
            new_name='UploadAssignment',
        ),
    ]
