# Generated by Django 3.0.3 on 2020-06-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200611_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='vi',
            new_name='video',
        ),
    ]
