# Generated by Django 3.0.3 on 2020-06-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_extendeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extendeduser',
        ),
    ]
