# Generated by Django 3.0.3 on 2020-06-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_extendeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
